name: forest5
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scipy
  - plotly
  - joblib
  - tzdata
  - pip:
      - openai>=1
      - python-dotenv
      # - ruff
      # - pytest
