name: forest5
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scipy
  - plotly
  - joblib>=1.4,<2.0
  - pydantic>=2.8,<3.0
  - pyyaml>=6.0.1,<7.0
  - structlog>=24.1,<25.0
  - tzdata
  - setuptools>=78.1.1
  - pip:
      - openai>=1
      - python-dotenv
      # - ruff
      # - pytest
