broker:
  type: "mt4"  # "paper" for tests
  bridge_dir: "${FOREST_MT4_BRIDGE_DIR}"  # set via $FOREST_MT4_BRIDGE_DIR or path to MQL4/Files/forest_bridge
  symbol: "EURUSD"
  volume: 0.01
  timeframe: "M1"

risk:
  risk_per_trade: 0.005
  max_drawdown: 0.20  # halt after 20% equity loss; adjust conservatively
  on_drawdown:
    action: "halt"  # or "soft_wait"

ai:
  enabled: false
  model: "gpt-4o-mini"
  max_tokens: 200
  context_file: "context.txt"  # use absolute path; on Windows/Wine use Z:\\path\\to\\context.txt
decision:
  min_confluence: 0.0
  tie_epsilon: 0.05
  weights:
    tech: 1.0
    ai: 0.75
  tech:
    default_conf_int: 0.50
    conf_floor: 0.10
    conf_cap: 1.00
time:
  model:
    enabled: false  # true when using a trained time filter model
    path: "${FOREST_TIME_MODEL_PATH}"  # e.g., /models/time_model.pkl
    q_low: 0.1
    q_high: 0.9

  primary_signal:
    strategy:
      compat_int: true  # false to return full TechnicalSignal instead of -1/0/1
      params:
        name: "h1_ema_rsi_atr"
        ema_fast: 21
        ema_slow: 55
        atr_period: 14
        rsi_period: 14
        t_sep_atr: 0.5
        pullback_atr: 0.5
        entry_buffer_atr: 0.1
        sl_atr: 1.0
        rr: 2.0
    patterns:  # candlestick pattern filters; disable any to skip its detector
      engulf:
        enabled: true  # disable to ignore engulfing candles
      pinbar:
        enabled: true  # disable to ignore pinbar patterns
      star:
        enabled: true  # disable to ignore morning/evening star patterns

backtest:
  tp_sl_priority: SL_FIRST   # or TP_FIRST
  setup_ttl_bars: 1
